name: Sync
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git clone https://github.com repo
          cd repo
         run: git push --force https://NickClickCasas:$HF_TOKEN@huggingface.co/spaces/NickClickCasas/Denia-Property-Care.git main
